<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Turpinverse.Core\Turpinverse.Core.csproj" />
    <ProjectReference Include="..\Turpinverse.ServiceDefaults\Turpinverse.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Turpinverse.Data\Turpinverse.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <Target Name="BuildTailwindCss" BeforeTargets="Build" Condition="Exists('$(MSBuildProjectDirectory)\package.json')">
    <Exec Command="npm ci" WorkingDirectory="$(MSBuildProjectDirectory)" Condition="!Exists('$(MSBuildProjectDirectory)\node_modules\tailwindcss')" />
    <Exec Command="npm run build:css" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>

</Project>
